### ISSUE TITLE
Please add a license and a screen shot

### ISSUE THREAD

**Issue by unixorn** [SomethingGeneric/zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I only add themes with screen shots in the readme so that users can see what they look like without having to install them.

Also, please add a license file, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

The plugin's name is very generic. Please consider renaming it to something descriptive - the theme files are named `matt` and `matt-ubuntu`, perhaps name the repository `matt-theme`?

Finally, don't take these as criticisms of the work you've done, they're meant to make a more useful entry in the plugin/theme list.

Thanks!

**Comment by SomethingGeneric** [comment]
Hey! Thanks for the suggestions. I've added the MIT license and a screenshot. While I appreciate that you want to add it to the plugins list, I'm not quite sure that's fair since it's just a copy of one of the default themes that I changed the colors of ever so slightly.

**Comment by unixorn** [comment]
ok, I can leave it out if you prefer.
